### PR TITLE
Port to dune

### PR DESCRIPTION
**Pull request by rgrinberg**
This build system is much faster and requries no generated files. Also
mparser.pcre and mparser.re have been split to their own sub libraries.
This allows users to more precisely express their dependency on mparser
and avoid the pitfalls of optional dependencies.

### CODE REVIEW

**Comment by rgrinberg** [comment]
@murmour ping?

**Comment by murmour** [comment]
Hi, Rudi.

Forgive my late answer. I've been scarce on time lately.

Thanks a lot for the contribution. I'll give it proper attention this weekend. This might be my perfect opportunity to get familiar with Dune, finally (I've always wanted to).

On splitting the library: it makes sense, yes. I've never liked the way OASIS handles optionality.

By the way, the unreleased version of MParser (2.0) includes a built-in regexp engine, which is faster than both RE and PCRE, and should satisfy most practical needs, feature-wise. I'll think about cherry-picking that change into a minor release (1.3), along with a switch to Dune. If I'm not mistaken about "most practical needs", then "mparser-re" and "mparser-pcre" packages will get near-zero install counts on OPAM, and will eventually be ditched in future releases.

**Comment by rgrinberg** [comment]
Excited to see your new regex engine. Sure, mparser-{re,pcre} can be deprecated in time. As far as I know mparser_pcre is actually used in the “rotor” refactoring tool so there might not be a need to rush.

Feel free to ask me any dune related questions. Welcome back :)

**Comment by murmour** [comment]
I took time to get familiar with Dune, and the overall impression is great: it feels more polished and powerful than OASIS+OCamlBuild.

My main concern is backward compatibility.

I've tried building and installing MParser from your branch, and it failed:

1) The generated .opam files require OPAM 2.0, while I have 1.2, in Ubuntu 18.04 LTS (same as in Debian Stretch). Given the popularity of this platform, I'd say that OPAM 1.2 is the compatibility baseline. Can Dune generate .opam files using an older format? If it can't, then these files should be written by hand (for now).

2) Running `dune build -p mparser` prints: `Error: Version 1.11 of dune is not supported. Supported versions: - 0.0 - 1.0 to 1.2`. With OCaml 4.06.1, OPAM gives me Dune 1.2.1. Could the project file be backported to Dune 1.2.1? It's just one year old, [and gets thousands of installs](https://opam.ocaml.org/packages/dune/dune.1.2.1/). By the way, a reasonable lower bound on the version of OCaml to support is at least 4.02 (comes with LTS versions of popular Linux distros). Dune does support that, right? Then why doesn't OPAM give me the latest version of Dune?

**Comment by rgrinberg** [comment]
Hi Max, many thanks for trying out dune. Glad you think we’re moving in the right direction from oasis/ocamlbuild.
> The generated .opam files require OPAM 2.0, while I have 1.2, in Ubuntu 18.04 LTS (same as in Debian Stretch). Given the popularity of this platform, I'd say that OPAM 1.2 is the compatibility baseline. Can Dune generate .opam files using an older format? If it can't, then these files should be written by hand (for now).

While this point stands, it’s unfortunately the least of your problems for supporting opam 2.0. The issue is that the current opam repositroy only accepts opam 2.0 packages. You will be unable to submit a new version of mparser until you update your .opam file to 2.0. In fact, that’s really the only reason I added the generation of opam files: to update the version of your opam metadata.

Regarding Linux distros, this .opam file should not be relevant for packaging anyway I suppose. Dune does not rely on it for anything so it does not matter what’s in it or even if it’s there.

> Running dune build -p mparser prints: Error: Version 1.11 of dune is not supported. Supported versions: - 0.0 - 1.0 to 1.2. With OCaml 4.06.1, OPAM gives me Dune 1.2.1. Could the project file be backported to Dune 1.2.1? It's just one year old, and gets thousands of installs. By the way, a reasonable lower bound on the version of OCaml to support is at least 4.02 (comes with LTS versions of popular Linux distros). Dune does support that, right? Then why doesn't OPAM give me the latest version of Dune?

Indeed it should be possible. Just make sure that the project version is set to (lang dune 1.2). Dune supports OCaml 4.02 in all 1.x versions. The reason why dune 1.2.1 gets so many installs is because it’s the last version that works on the multicore branch :) Dune 1.3 introduced threads to handle signals better, and multicore does not support OCaml’s thread api at the moment.

To give my personal (and unsolicited) opinion on this matter: users who install packages from their distro’s package manager rarely except the latest version of such packages. I don’t think there’s anything wrong in making them wait a bit to get the latest version of a library.

Cheers,

Rudi.

**Comment by murmour** [comment]
Rudy, hello again!

I'm convinced by your arguments. Merging the change. Thank you!

Adding the [official OPAM PPA](https://launchpad.net/~avsm/+archive/ubuntu/ppa) to Ubuntu 18.04 got me OPAM 2.0.4 and Dune 1.11.4. I guess that's what should everyone else do.

**Comment by rgrinberg** [comment]
Awesome! Looking forward to see this released on opam.

**Pull request merged**
